---
sudo: required
dist: xenial

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.3.0.0
  - ANSIBLE_VERSION=2.2.2.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-simplejson
  - sudo mkdir /etc/systemd/system

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check playbook.yml

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -v --connection=local -D -b -i 'localhost,' playbook.yml

  - >
    ansible-playbook -v --connection=local -D -b -i 'localhost,' playbook.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)