---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: setup group
  group:
    name: '{{ monasca_group }}'
    system: yes

- name: Setup user
  user:
    name: '{{ monasca_agent_user }}'
    system: yes
    group: '{{ monasca_group }}'

- name: create upstart script from template
  template:
    dest: '/etc/init/{{ item }}'
    owner: root
    group: root
    mode: 0744
    src: '{{ item }}.j2'
  notify:
    - restart monasca-agent
  with_items:
    - monasca-collector.conf
    - monasca-statsd.conf
    - monasca-forwarder.conf

- name: create placeholder script for monasca-agent
  copy:
    dest: /etc/init.d/monasca-agent
    owner: root
    group: root
    mode: 0744
    content: |
      #!/bin/bash
      exit 0

- name: create monasca install directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ monasca_agent_user }}'
    group: root
    mode: 0775
    recurse: no
  with_items:
    - '{{ agent_log_dir }}'
    - '{{ agent_conf_dir }}'
    - '{{ agent_conf_dir }}/conf.d'
    - '{{ agent_custom_plugin_dir }}'
    - '{{ agent_custom_conf_dir }}'

- name: Stop monasca-agent service
  service:
    name: monasca-agent
    state: stopped
    enabled: no
  ignore_errors: yes
