---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: setup group
  group:
    name: '{{ monasca_group }}'
    system: yes

- name: Setup user
  user:
    name: '{{ monasca_agent_user }}'
    system: yes
    group: '{{ monasca_group }}'

- name: create upstart script from template
  template:
    dest: '/etc/systemd/system/{{ item }}.service'
    owner: root
    group: root
    mode: 0744
    src: '{{ item }}.service.j2'
  notify:
    - reload systemd
  with_items:
    - monasca-collector
    - monasca-statsd
    - monasca-forwarder

- name: create monasca install directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ monasca_agent_user }}'
    group: root
    mode: 0775
    recurse: no
  with_items:
    - '{{ monasca_agent_log_dir }}'
    - '{{ monasca_agent_conf_dir }}'
    - '{{ monasca_agent_conf_dir }}/conf.d'
    - '{{ monasca_agent_custom_plugin_dir }}'
    - '{{ monasca_agent_custom_conf_dir }}'

###
# This is workaround around monasca-setup creating monasca-agent init script during every run.
- name: create placeholder script for monasca-agent
  copy:
    dest: /etc/init.d/monasca-agent
    owner: root
    group: root
    mode: 0744
    content: |
      #!/bin/bash
      exit 0

- name: Stop monasca-agent service
  service:
    name: monasca-agent
    state: stopped
    enabled: no
  ignore_errors: yes
###


- name: Deploy agent config
  template:
    src: agent.yaml.j2
    dest: /etc/monasca/agent/agent.yaml
  notify:
    - restart monasca-agent