---
#
# XXX:
# Make this installation per plugin we need to be able to specify
# particular plugins we want to deploy. As right now there is no
# proper way to configure them
#
#

- name: Install monasca-agent dependiences
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    force: yes
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python-virtualenv
    - pkg-config
    - zlib1g-dev
    - libxml2
    - libxml2-dev
    - libxslt1.1
    - libxslt1-dev
    - git

- name: create monasca-agent install directory
  file:
   path: '{{ item }}'
   state: directory
   owner: root
   mode: 0775
  with_items:
    - '{{ agent_install_dir }}'

- name: Install monasca-agent packages
  pip:
    name: '{{ item.name }}'
    version: '{{ item.version | default(omit) }}'
    extra_args: '{{ item.args | default(omit) }}'
    virtualenv_command: virtualenv
    virtualenv: '{{ agent_install_dir }}'
  with_items:
    - name: "git+https://github.com/openstack/monasca-agent.git@{{ monasca_agent_revision | default(master) }}"
    - name: psutil
    - name: lxml

