---
#
# XXX:
# Make this installation per plugin we need to be able to specify
# particular plugins we want to deploy. As right now there is no
# proper way to configure them
#
#

- name: Install monasca-agent dependiences
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    force: yes
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python-virtualenv
    - pkg-config
    - libz-dev
    - libxml2
    - libxml2-dev
    - libxslt1.1
    - libxslt1-dev

- name: create monasca-agent install directory
  file:
   path: '{{ item }}'
   state: directory
   owner: root
   mode: 0775
  with_items:
    - '{{ agent_install_dir }}'

- name: Install monasca-agent packages
  pip:
    name: '{{ item.name }}'
    version: '{{ item.version | default(omit) }}'
    extra_args: '{{ item.args | default(omit) }}'
    virtualenv_command: virtualenv
    virtualenv: '{{ agent_install_dir }}'
  with_items:
    - name: monasca-agent
      version: 1.1.24
    - name: psutil
    - name: lxml

#
# TODO: this should be checked after influxdb/agent update
- name: UI - Patch monasca-ui with next-page fix
  patch:
    strip: 1
    src: patches/http_check_return_html.diff
    basedir: '{{ agent_install_dir }}/lib/python2.7/site-packages/monasca_agent'
