---
- name: Install plugin dependencies if needed
  include: '{{ plugin_file }}'
  with_first_found:
    - files:
        - 'plugins/{{ plugin }}.yml'
      skip: true
  loop_control:
    loop_var: plugin_file

- name: Create plugin configuration file
  template:
   dest: '{{ monasca_agent_plugin_conf_dir }}/{{ plugin }}.yaml'
   owner: '{{ monasca_agent_user }}'
   group: '{{ monasca_group }}'
   mode: 0640
   src: 'plugins/{{ plugin }}/{{ plugin }}.yaml.j2'
  notify:
    - restart monasca-agent
