---
- name: Start and enable monasca-agent services
  service:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - monasca-forwarder
    - monasca-statsd
    - monasca-collector
  when: monasca_agent_services_start
