---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Start and enable monasca-agent
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
#    - monasca-agent
    - monasca-forwarder
    - monasca-statsd
    - monasca-collector
