---

- name: restart monasca-agent
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
#    - monasca-agent
    - monasca-forwarder
    - monasca-statsd
    - monasca-collector

- name: reload systemd
  command: systemctl daemon-reload